---

- name: Update apt cache.
  apt:
    update_cache: true
    cache_valid_time: 600
  when: ansible_os_family == 'Debian'
  changed_when: false
  
- name: Java Fix for Debian bug
  file:
    path:  /usr/share/man/man1/
    state: directory

- name: install Minecraft dependencies
  apt:
    name: "{{ dependencies }}"
    state: present
    install_recommends: false
    update_cache: true
    default_release: "{{ (ansible_distribution_release == 'jessie') | ternary('jessie-backports', omit) }}"

- name: install Spigot dependencies
  apt:
    name: ['git', 'tar']
  when: minecraft_server_type == 'spigot'
