---
- name: install Minecraft dependencies
  yum:
    name: "{{ dependencies }}"
    state: present

- name: install Spigot dependencies
  yum:
    name: ['git', 'tar']
  with_items:
    - git
    - tar
  when: minecraft_server_type == 'spigot'
