---

- name: build Spigot server
  command: "java -jar BuildTools.jar --rev {{ minecraft_version_latest | default(minecraft_version) }}"
  args:
    chdir: "{{ minecraft_home }}/build"
  environment:
    SHELL: /bin/bash
  become: true
  become_user: "{{ minecraft_user }}"

- name: symlink Spigot server
  file:
    src: "{{ item }}"
    path: "{{ minecraft_home }}/spigot.jar"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    state: link
  with_fileglob: " {{ minecraft_home }}/build/spigot*.jar"
  become: true
  notify:
    - restart Minecraft

- name: agree to EULA
  copy:
    src: eula.txt
    dest: "{{ minecraft_home }}/eula.txt"
    mode: 0644
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
  notify:
    - enable service
