---
# Chain handlers to support multiple process supervisors. A task simply needs
# to notify 'restart Minecraft', which will trigger the supervisor-specific
# actions.
- name: restart Minecraft
  debug:
    msg: restarting Minecraft using {{ minecraft_process_control }}
  changed_when: true
  notify:
    - restart Minecraft

- name: restart Minecraft
  service:
    name: "{{ minecraft_service_name }}"
    state: restarted
    daemon_reload: true
  when: minecraft_process_control == 'systemd'

- name: enable service
  debug:
    msg: enabling Minecraft service using {{ minecraft_process_control }}
  changed_when: true
  notify:
    - enable service

- name: enable service
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - "{{ minecraft_service_name }}.service"
    - "{{ minecraft_service_name }}.socket"
  when: minecraft_process_control == 'systemd'
