---
- name: Converge
  hosts: all
  become: true

  vars:
    minecraft_server_type: minecraft
    minecraft_version: latest
    minecraft_max_memory: 2048M
    minecraft_server_properties:
      server-port: 25565
      rcon.port: 25564

  roles:
    - role: ansible-role-minecraft
