---
- name: Converge
  become: true

  vars:
    minecraft_server_type: spigot
    minecraft_version: latest
    minecraft_max_memory: 2048M
    minecraft_server_properties:
      server-port: 25565
      rcon.port: 25564

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: ansible-role-minecraft
