---

- name: create Spigot build directory
  file:
    path: "{{ minecraft_home }}/build"
    state: directory
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0755

- name: download Spigot build tools
  get_url:
    url: "{{ minecraft_spigot_url }}"
    dest: "{{ minecraft_home }}/build"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: 0755
